# *Importing Modules*

In [1]:
import pandas as pd
import numpy as np

# *Series*

In [2]:
# create series 
my_series=pd.Series([1,2,3,4,5])
my_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
my_series=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [4]:
my_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
my_series['a']

1

In [6]:
my_series[:3]

a    1
b    2
c    3
dtype: int64

In [7]:
'a' in my_series

True

In [8]:
2 in my_series

False

In [9]:
my_series.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [10]:
my_series.values

array([1, 2, 3, 4, 5], dtype=int64)

In [11]:
for item in my_series.values:
    print(item)

1
2
3
4
5


In [12]:
my_series=pd.Series({'a':1,'b':2,'c':8})
my_series

a    1
b    2
c    8
dtype: int64

# *DataFrame*

In [13]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['a','b','c'])
df

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
df['d']=df['a']+df['c']
df

a  b  c   d
0  1  2  3   4
1  4  5  6  10
2  7  8  9  16

In [17]:
df[['a','d']]

a   d
0  1   4
1  4  10
2  7  16

In [18]:
df.iloc[:,1]

0    2
1    5
2    8
Name: b, dtype: int64

In [19]:
df.loc[:,'d']

0     4
1    10
2    16
Name: d, dtype: int64

In [20]:
df.drop('d',axis=1,inplace=True)
df

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [21]:
df.drop(2,axis=0,inplace=True)
df

a  b  c
0  1  2  3
1  4  5  6

In [22]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [23]:
df.values

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [24]:
df['b'].get(0)

2

In [26]:
df.reset_index()
df

a  b  c
0  1  2  3
1  4  5  6

In [27]:
df.index=[12,13]
df

a  b  c
12  1  2  3
13  4  5  6

In [29]:
df.reset_index(inplace=True)
df

index  a  b  c
0     12  1  2  3
1     13  4  5  6

In [30]:
df.drop('index',axis=1,inplace=True)

In [31]:
df

a  b  c
0  1  2  3
1  4  5  6

In [32]:
df.rename(columns={'a':'A'},inplace=True)
df

A  b  c
0  1  2  3
1  4  5  6

In [34]:
df[df['A']>3]

A  b  c
1  4  5  6

In [35]:
df[(df['b']>2 )& (df['c']>3)]

A  b  c
1  4  5  6

In [36]:
df.set_index('c',inplace=True)

In [37]:
df

A  b
c      
3  1  2
6  4  5

In [38]:
df.reset_index(inplace=True)
df

c  A  b
0  3  1  2
1  6  4  5

# *Missing Values*

In [39]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [56]:
df.isnull().sum()

A    0
B    2
C    0
dtype: int64

In [40]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [41]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [42]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [43]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [45]:
df['A'].fillna(9,inplace=True)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  9.0  NaN  3

# *Operations*

In [46]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  9.0  NaN  3

In [47]:
df["A"].value_counts()

A
1.0    1
2.0    1
9.0    1
Name: count, dtype: int64

In [48]:
df['B'].value_counts()

B
5.0    1
Name: count, dtype: int64

In [51]:
df['B'].unique()

array([ 5., nan])

In [52]:
df['B'].nunique()

1

In [54]:
df['A'].apply(lambda x: x**2)

0     1.0
1     4.0
2    81.0
Name: A, dtype: float64

In [55]:
df['A']=df['A'].apply(lambda x: x**2)
df

A    B  C
0   1.0  5.0  1
1   4.0  NaN  2
2  81.0  NaN  3

In [57]:
df.sort_values(by='A',ascending=False)

A    B  C
2  81.0  NaN  3
1   4.0  NaN  2
0   1.0  5.0  1

In [58]:
df

A    B  C
0   1.0  5.0  1
1   4.0  NaN  2
2  81.0  NaN  3

In [59]:
df.sort_values(by='A',ascending=False,inplace=True)

In [60]:
df

A    B  C
2  81.0  NaN  3
1   4.0  NaN  2
0   1.0  5.0  1

In [62]:
df.reset_index(inplace=True)
df.drop('index',axis=1,inplace=True)
df

A    B  C
0  81.0  NaN  3
1   4.0  NaN  2
2   1.0  5.0  1

# *Numerical and Categorical Columns*

In [63]:
df.select_dtypes(include=np.number)

A    B  C
0  81.0  NaN  3
1   4.0  NaN  2
2   1.0  5.0  1

In [64]:
df.select_dtypes(include='object')

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [65]:
df['D']=['yousef','mahmoud','mohamed']
df.select_dtypes(include=np.number)

A    B  C
0  81.0  NaN  3
1   4.0  NaN  2
2   1.0  5.0  1

In [66]:
df

A    B  C        D
0  81.0  NaN  3   yousef
1   4.0  NaN  2  mahmoud
2   1.0  5.0  1  mohamed

In [68]:
df.select_dtypes(include='object').columns

Index(['D'], dtype='object')

In [69]:
df.select_dtypes(include=np.number).columns

Index(['A', 'B', 'C'], dtype='object')